repos:
- repo: local
  hooks:
  - id: MyTests
    name: Run my tests
    entry: python
    language: system
    args: [pre_commit_tests.py]

repos:
- repo: local
  hooks:
  - id: MyTests
    name: Run my tests
    entry: python
    language: system
    args: [post_commit_tests.py]

repos:
- repo: local
  hooks:
  - id: MyTests
    name: Run my tests
    entry: python
    language: system
    args: [pre_push_tests.py]
    stages: [push]

repos:
- repo: local
  hooks:
  - id: MyTests
    name: Run my tests
    entry: python
    language: system
    args: [commit_message_tests.py]
    stages: [commit-msg]
